server:
  port: 9002
  
spring:
  application:
    name: servicio-empleados

eureka:
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defautlZone: http://localhost:8761/eureka
